// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6ogMFyM1ksqJCl35p776jFia6bobYxY',
    appId: '1:904248222855:web:217a14702d1bf2acdf8422',
    messagingSenderId: '904248222855',
    projectId: 'charitable-gaming-dev',
    authDomain: 'charitable-gaming-dev.firebaseapp.com',
    storageBucket: 'charitable-gaming-dev.appspot.com',
    measurementId: 'G-CN3WGSP11P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWzVWmiWQOkdnqUvK9ovA3ZQbr-0JdMKI',
    appId: '1:904248222855:android:5a60a6d5f4964e1ddf8422',
    messagingSenderId: '904248222855',
    projectId: 'charitable-gaming-dev',
    storageBucket: 'charitable-gaming-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKtCBBWon2azAj5rtBYykN8OxetFtNr4',
    appId: '1:904248222855:ios:5cef9cf544eac6f4df8422',
    messagingSenderId: '904248222855',
    projectId: 'charitable-gaming-dev',
    storageBucket: 'charitable-gaming-dev.appspot.com',
    iosClientId: '904248222855-iadjmv1b57rp52ohvjbkoiv9hp1iu1j0.apps.googleusercontent.com',
    iosBundleId: 'com.charitable-gaming.app',
  );
}
